version: 3.0.3

# Site settings
title: The Rami Method
baseurl: "" # the subpath of your site, e.g. /clientname
url: "http://lemon-stork1.cloudvent.net" # the base hostname & protocol for your site
permalink: /:year/:month/:title

# Build settings
safe: false

gems:
  - jekyll-bootstrap-sass