version: 3.0.3

# Site settings
title: The Rami Method
baseurl: "/rami" # the subpath of your site, e.g. /clientname
url: "http://ocupopdev.com" # the base hostname & protocol for your site

# Build settings
safe: false

source: src

gems:
  - jekyll-bootstrap-sass